#!/usr/bin/env bash
# This script will display number 1-100 and will display fizzbuzz when its a multiple of 3&5, fizz when its a multiple of 3, and buzz when the number is a multiple of 5
x=1
while [ $x -le 100 ]
do
	if (( x % 15 == 0 ))
	then
		echo "FizzBuzz"
	elif (( x % 3 == 0 ))
	then
		echo "Fizz"
	elif (( x % 5 == 0 ))
	then
		echo "Buzz"
	else
		echo "$x"
	fi
	x=$(( x + 1 ))
done
