#!/usr/bin/env bash
# This script displays 'Best School' 10 times except for the 9th iteration which says 'Hi'
while [ $x -le 10 ]
do
	if [ $x = 9 ]
	then
		echo "Hi"
	else
		echo "Best School"
	fi
done
