#!/usr/bin/env bash
# This script displays 'Best School' 10 times and on the 9th iteration says 'Hi'
x=1
while [ $x -le 10 ]
do
	if [ $x = 9 ]
	then
		echo "Best School"
		echo "Hi"
		x=$(( x + 1 ))
	else
		echo "Best School"
		x=$(( x + 1 ))
	fi
done
