#!/usr/bin/env bash
# This script will create 10 lines with "bad luck" on the 4th line, "good luck" on the 8th line, and "Best School" for the rest
x=1
while [ $x -le 10 ]
do
	if [ $x = 4 ]
	then
		echo "bad luck"
		x=$(( x + 1 ))
	else
		if [ $x = 8 ]
		then
			echo "good luck"
			x=$(( x + 1 ))
		else
			echo "Best School"
			x=$(( x + 1 ))
		fi
	fi
done
