#!/usr/bin/env bash
# this script will display time for 12 hours and 59 minutes
h=0
while [ $h -le 12 ]
do
	m=1
	echo "Hour: $h"
	h=$(( h + 1 ))
	while [ $m -le 59 ]
	do
		echo "$m"
		m=$(( m + 1 ))
	done
done
