#!/usr/bin/bash
# This script will display the contents of the current directory, in list format, only the name after the dash
content=0
list=$(ls)
for content in $list
do
echo "$content" | cut -d "-" -f2
done
